---
# Default variables for the wordpress role.

wordpress_image: "wordpress:fpm-alpine"
mariadb_image: "mariadb:lts"

# MariaDB tuning
mariadb_max_allowed_packet: "67108864"

# Force re-deploy even when no template changes are detected
force_restart: false
