---
# Default variables for the proxy role.

proxy_caddy_image: "salbr/caddy-desec:v2.11.3"
proxy_socket_proxy_image: "linuxserver/socket-proxy:latest"

# Force re-deploy even when no template changes are detected
proxy_force_restart: false
