---
- name: Check if App stacks exist before stopping
  ansible.builtin.stat:
    path: "{{ stack_root }}/{{ item }}/docker-compose.yml"
  loop: "{{ enabled_apps }}"
  register: compose_files

- name: Shut down App stacks
  community.docker.docker_compose_v2:
    project_src: "{{ stack_root }}/{{ item.item }}"
    state: absent  # This is the equivalent of 'docker compose down'
  loop: "{{ compose_files.results }}"
  when: item.stat.exists
