---
- name: Ensure stack directories exist
  ansible.builtin.file:
    path: "{{ stack_root }}/{{ item }}"
    state: directory
    mode: '0755'
  loop: "{{ enabled_apps }}"

- name: Prepare Application data
  ansible.builtin.copy:
    src: "mealie_prompts/"
    dest: "{{ storage_root }}/mealie/prompts/"
    owner: '1000'
    group: '1000'
    mode: '0755'
  ignore_errors: true

- name: Deploy Docker Compose templates
  ansible.builtin.template:
    src: "{{ item }}.yml.j2"
    dest: "{{ stack_root }}/{{ item }}/docker-compose.yml"
    mode: '0644'
  loop: "{{ enabled_apps }}"
  register: compose_templates

- name: Start Docker Stacks
  community.docker.docker_compose_v2:
    project_src: "{{ stack_root }}/{{ item.item }}"
    state: present
    pull: always
  loop: "{{ compose_templates.results }}"
  # Only runs the 'up' command if the template file was changed
  when: item.changed or force_restart | default(false)
