---
- name: Ensure Media stack directories exist
  ansible.builtin.file:
    path: "{{ stack_root }}/{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - wordpress
    - tubearchivist

- name: Deploy Media Compose templates
  ansible.builtin.template:
    src: "{{ item }}.yml.j2"
    dest: "{{ stack_root }}/{{ item }}/docker-compose.yml"
  loop:
    - wordpress
    - tubearchivist
  register: media_composes

- name: Start Media Stacks
  community.docker.docker_compose_v2:
    project_src: "{{ stack_root }}/{{ item.item }}"
    state: present
    pull: always
  loop: "{{ media_composes.results }}"
  when: item.changed or force_restart | default(false)
