---
- name: Create Aria2 stack directory
  ansible.builtin.file:
    path: "{{ stack_root }}/aria2"
    state: directory
    owner: 0
    group: 0
    mode: '0755'

- name: Deploy Aria2 Compose
  ansible.builtin.template:
    src: aria2.yml.j2
    dest: "{{ stack_root }}/aria2/docker-compose.yml"
    mode: '0644'
  register: aria2_compose

- name: Start/Update Aria2
  community.docker.docker_compose_v2:
    project_src: "{{ stack_root }}/aria2"
    state: present
    pull: always
  when: aria2_compose.changed or force_restart
  tags: [molecule-notest]
